export const svg = {
  groupName: "SVG",
  emptyLineBefore: "threshold",
  noEmptyLineBetween: true,
  properties: [
    "alignment-baseline",
    "baseline-shift",
    "clip-path",
    "clip-rule",
    "color-interpolation",
    "color-interpolation-filters",
    "color-rendering",
    "dominant-baseline",
    "fill",
    "fill-opacity",
    "fill-rule",
    "flood-color",
    "flood-opacity",
    "glyph-orientation-horizontal",
    "glyph-orientation-vertical",
    "image-rendering",
    "lighting-color",
    "marker-end",
    "marker-mid",
    "marker-start",
    "mask",
    "paint-order",
    "shape-rendering",
    "stop-color",
    "stop-opacity",
    "stroke",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-opacity",
    "stroke-width",
    "text-anchor",
  ],
};
